trigger:
- master

pr:
  branches:
    include:
      - master

pool: default

steps:
- script: |
    echo "Starting pipeline..."
  displayName: "Start"

- task: UseNode@1
  inputs:
    version: "18.x"
  displayName: "Use Node.js 18"

- script: |
    npm install --legacy-peer-deps
  displayName: "Install dependencies"

- script: |
    echo "Deploying project..."
    rsync -rv --delete --no-times --omit-dir-times \
      --exclude ".git" \
      --exclude "node_modules" \
      --exclude ".env" \
      $(Build.SourcesDirectory)/ /home/proy_dev/landinpageexample/
  displayName: "Copy project"

- script: |
    cd /home/proy_dev/landinpageexample
    npm install --production --legacy-peer-deps
  displayName: "Install production dependencies"

- script: |
    pm2 restart testweb
  displayName: "Restart PM2"